### ISSUE TITLE
Insert batch: created_at error

### ISSUE THREAD

**Issue by spacecomx** [mesqueeb/VuexEasyFirestore#17]
An firebase error is thrown  when not using the **firestorePath: 'users/{userId}/data** as the path but instead for example: 

```javascript
const userModule = {
  firestorePath: 'users',
  firestoreRefType: 'collection',
  moduleName: 'userData',
  statePropName: 'docs',
  // the rest of your module here
}
```
When using any of the following two options: 
```
dispatch('userData/set', doc)
dispatch('userData/insert', doc)
```
The insert fails due to the `created_at` field not having `{userId}` passed in. It was never included as it was not set in as part of the firestorePath config.  Its when inserting into a batch in file **index.es.js on line 397**.

The reason it was **never set** is related to `line 988` that looks for the `{userId}` in the path. If not found the userid is not set. 

```
  inserts.forEach(function (item) {
    item.created_at = Firebase.firestore.FieldValue.serverTimestamp();
    item.created_by = userId;
    var newRef = dbRef.doc(item.id);
    batch.set(newRef, item);
  });
```

The temp edited snippet of the code that works when fetching the uid directly off the Firebase instance.
```
  inserts.forEach(function (item) {
    item.created_at = Firebase.firestore.FieldValue.serverTimestamp();
    item.created_by = Firebase.auth().currentUser.uid;
    var newRef = dbRef.doc(item.id);
    batch.set(newRef, item);
  });
```
The reason for not including the `{userId}` in the firestorePath is to avoid having to use **sub-collections** and that we use  **signIn anonymously users** that wont have their data nested under their own userId. Instead would use the `created_by` field to fetch a single users records from a specific collection.

Hope this helps explain, kindly :)

**Comment by mesqueeb** [comment]
@spacecomx is your user logged in? Or are you trying to use it without firebase authentication?

**Comment by mesqueeb** [comment]
@spacecomx I removed the dependency on the `userId`.
The `created_by` field now should show `null` or the correct id.

Please try `npm i --save vuex-easy-firestore@latest` and let me know if it fixed your problem.

**Comment by spacecomx** [comment]
Hi Luca,

I had created a email and password authenticated user through Firebase. This is when I picked up the error. The created_by field will help me filter all records by that user. I will need the created_by field. The plan is we are building at cart with menus, menu_items and menu_sides and favourites each as its own collection, each will have a userid (create_by field). The attached image is a example but its users for the test.

The plan is to use a anonymous userId to track the users selection and/or added menus tracked the created_by field. We will store the anonymous userId in cookie until such time as the visitor is ready to checkout (same or day or at a later date). What I want to know is if the created_by field can still be used this way. Im sure it shouldn’t matter if we have a signed in user.

One other thing is how do you fire the openDBChannel to only initialise those records associated with that logged in user?  

Kind regards,

Wayne Gibson, Director
SpaceComX, Creative Design | Marketing | Web Agency | Mobile: +27 (72) 685 8551
PO Box 3786, Dainfern, Johannesburg, 2055, South Africa
Division of SpaceCom Alliance (Pty) Ltd

**Comment by spacecomx** [comment]
Hi Luca,

Thank you so much for the feedback and the swift fix. Thank you very much for taking the time to assist us. Its very much appreciated :)

We have tested with both a normal signed in fire auth user and a signInAnonymously user. .  They both work and record the userId for each correctly. 

Just the open channel question if you would be so kind to give me feedback on.

Kindly,

Wayne Gibson, Director
SpaceComX, Creative Design | Marketing | Web Agency | Mobile: +27 (72) 685 8551
PO Box 3786, Dainfern, Johannesburg, 2055, South Africa
Division of SpaceCom Alliance (Pty) Ltd

**Comment by spacecomx** [comment]
For your reference: After the fix.  Working correctly . 

Wayne Gibson, Director
SpaceComX, Creative Design | Marketing | Web Agency | Mobile: +27 (72) 685 8551
PO Box 3786, Dainfern, Johannesburg, 2055, South Africa
Division of SpaceCom Alliance (Pty) Ltd

**Comment by mesqueeb** [comment]
@spacecomx 
Please see the section on [filters](https://github.com/mesqueeb/VuexEasyFirestore#filters)

In your case you can add these settings to your vuex module:
```js
  // make sure you authenticate the user first
  const userId = Firebase.auth().currentUser.uid
  // in your module
  sync: {
    where: [['created_by', '==', userId]],
  }
```
Please note that this is only for the openDBChannel. If you need just to fetch records without auto-syncing you can use the [fetch action](https://github.com/mesqueeb/VuexEasyFirestore#fetching) I prepared.

Please note that it will retrieve no records if there are no records with that userId or if you forget to index your firestore on that field in the firestore settings. (they'll give you a hint in the console.log how to do so if I recall correctly.)

Let me know how it went and if I can be of any other assistance!!

PS: I can imagine it's difficult to get the correct userId in this case, so I'll patch a method where you can use `'{userId}'` in here and it'll get swapped out just at the start of when openDBChannel runs.

**Comment by mesqueeb** [comment]
@spacecomx Did it work out? Let me know if you have any issues. You can also find me on twitter @mesqueeb
