### ISSUE TITLE
Firebase warning

### ISSUE THREAD

**Issue by aceofpack** [mesqueeb/VuexEasyFirestore#22]
This might need considering:

```The behavior for Date objects stored in Firestore is going to change
AND YOUR APP MAY BREAK.
To hide this warning and ensure your app does not break, you need to add the
following code to your app before calling any other Cloud Firestore methods:

  const firestore = firebase.firestore();
  const settings = {/* your settings... */ timestampsInSnapshots: true};
  firestore.settings(settings);

With this change, timestamps stored in Cloud Firestore will be read back as
Firebase Timestamp objects instead of as system Date objects. So you will also
need to update code expecting a Date to instead expect a Timestamp. For example:

  // Old:
  const date = snapshot.get('created_at');
  // New:
  const timestamp = snapshot.get('created_at');
  const date = timestamp.toDate();

Please audit all existing usages of Date when you enable the new behavior. In a
future release, the behavior will change to the new behavior, so if you do not
follow these steps, YOUR APP MAY BREAK.```

**Comment by mesqueeb** [comment]
Yeah, to my knowledge that's a firebase related setting that you must make when you initiate firebase with your credentials, and BEFORE you initiate the vuex store with this plugin.

Is that possible in your design?

I'll need to update the docs to clarify this though. Thanks for the heads up!

**Comment by mesqueeb** [comment]
the library is now using the latest Firebase version. I am not seeing this issue any more.

**Comment by l2aelba** [comment]
@mesqueeb Can you check this warning again? I'm not sure this is from vuex-easy-firestore or mine.

![screenshot 2018-12-03 at 14 54 45](https://user-images.githubusercontent.com/983458/49377840-7a199d00-f70b-11e8-8004-d2ad43bb6f31.png)

**Comment by mesqueeb** [comment]
Hi @l2aelba 
This is because of the way you import firestore. Please read that error and double check all your import statements. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@l2aelba Actually, I found out there was one import in my library that had the old import method. I have just now updated the import method and this message should not appear anymore.

Please update to latest version: `npm i vuex-easy-firestore@latest`

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
