### ISSUE TITLE
sub collections

### ISSUE THREAD

**Issue by Bartonking** [mesqueeb/VuexEasyFirestore#28]
Excellent project.
  How do you work with subcollections when the key is a variable.

const userModule = {
  firestorePath: 'boats/{myBoatID}/data',
  firestoreRefType: 'collection', // or 'doc'
  moduleName: 'boats',
  statePropName: 'docs',
  // the rest of your module here
}

**Comment by mesqueeb** [comment]
@Bartonking I will make it this possible asap, however I want to know where you get your variable from? In case you get the variable before the instantiation of the vuex module you can just pass it directly inside the path. In case you get the variable after the vuex module instantiation I will have to think how to best pass it. That why I'd want to know where you get it from and if you save it somewhere else in the vuex store or not?

In this case however, remember that:
- the user will not be able to edit other boats (even if he owns multiple)
- in the case the user owns multiple boats you'll need a separate vuex module for each boat.

Is this your intended use case?

**Comment by mesqueeb** [comment]
@Bartonking
I have made this possible through custom variables passed as parameter like so: `dispatch('module/openDBChannel', {customVar: customId})`.

Please update to `npm i vuex-easy-firestore@1.9.0`
and check the new documentation [here](https://github.com/mesqueeb/VuexEasyFirestore#variables-for-firestorepath-or-filters).

Feel free to write additional feedback or comments, or if all good please close this issue!

**Comment by Bartonking** [comment]
hi, thanks.  When the user logs in I retrieve a list of boats that he has access to.  so I am making the call on the mounted() event of a page.

I am now seeing an error after the update.  "Firebase: Firebase service named 'firestore' already registered (app/duplicate-service)."   
 
![firestoreerror](https://user-images.githubusercontent.com/4013744/45004446-12946a00-afc3-11e8-8d17-da712dc18411.png)

**Comment by mesqueeb** [comment]
Dear Bartonking. I’m looking right into this. 

Could you let me know in which order you initialise things?
Eg. 
1. Initialise firebase
2. Initialise firebase auth listener
3. Initialise vuex store
4. openDBChannel

What’s the order for (3) in your case?

**Comment by mesqueeb** [comment]
@Bartonking I'm having trouble replicating this problem. It works fine in my apps.
Are you able to zip your app without the node_modules folder and send it to me? You can telegram or twitter DM me with @mesqueeb

Or if you have an open source repo let me know.

Also, try to first _instanciate vuex store_ then _initialise firebase_, see if that helps.

**Comment by Bartonking** [comment]
hey  issue fixed.  i removed the last two import statements
import firebase from 'firebase/app';
//  import 'firebase/auth'; - removed
//  import 'firebase/firestore'; - removed

Thanks so much.   you have an awesome package.

**Comment by DutchmanSA** [comment]
How do I use the above without using openDBChannel? I dont want to open and real time channel and only insert new records using a path like this:
firestorePath: 'mandates/{mandateId}/debtors',

**Comment by mesqueeb** [comment]
@DutchmanSA
Thanks for your question!
I updated the docs here:
https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#variables-for-firestorepath-or-filters

See `// 3. Dispatching setPathVars`

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
