### ISSUE TITLE
[Question] How to Auth with firestore

### ISSUE THREAD

**Issue by davidpiesse** [mesqueeb/VuexEasyFirestore#8]
Hi!
You have an example of how to connect to Firestore using the AuthStateChanged but is it possible to pass in a firebase object or config with a API key etc?
Basically can you connect to firebase the normal way?

Thanks for this package!
D

**Comment by mesqueeb** [comment]
Dear David Piesse,
Thank you for your comment!
In line with my vuex plugins:

- [vuex-easy-access](https://github.com/mesqueeb/VuexEasyAccess)
- vuex-easy-firestore (this one)

I'm currently working on a **vuex-easy-firebase-auth** plugin to easily setup the firebase authentication and have it saved in a vuex `user` module.

However, that package needs some more time until it's ready for beta release. : S

I do think that maybe I need some better documentation here as well for how to enable the firestore.

For now you I'll share you how I personally do it in my projects:

```js
// enable firestore with persistence
async function getFirestore () {
  const firestore = Firebase.firestore()
  firestore.settings({timestampsInSnapshots: true})
  try {
    await firestore.enablePersistence()
  } catch (err) {
    console.log('err.code → ', err.code)
    if (err.code === 'failed-precondition') {
      // Multiple tabs open, persistence can only be enabled in one tab at a a time.
      let message = store.getters.text.api['firebase/failed-precondition']
      notify({message, preset: 'error'})
    } else if (err.code === 'unimplemented') {
      // The current browser does not support all of the
      // features required to enable persistence
      return firestore
    }
  }
  return firestore
}

// =========>
// Start Firebase
// =========>
Firebase.initializeApp(firebaseConfig)
Firebase.auth().onAuthStateChanged(user => {
  getFirestore().then(db => {
    if (user) {
      // Signed in. Let Vuex Easy Firestore know.
      store.dispatch('module/path/openDBChannel') // open the DB channels
    } else {
      // Signed out. Let Vuex know.
      store.dispatch('resetStore', null)
    }
  })
})
```

**Comment by davidpiesse** [comment]
Awesome!
Thanks for spending the time with a full reply; I look forward to the next package!

I had a play last night and I had a simpler version of your method; which is great as I know am on the right path.

**Comment by mesqueeb** [comment]
@davidpiesse No problem!

Let me know if you are able to use this package well or run into any problems! I'll try help out as much as I can!
For now this plugin works for me. (However, I still need to add tests, but having trouble finding a good Firestore mock for testing...)

It's crucial to not forget to open the DB channel: `dispatch('module/path/openDBChannel')`

Please note I haven't tested when a user logs out and a different user logs in yet. I need to finish auto re-freshing the vuex store in that case, so for now you'd have to do something like `dispatch('resetStore')` and write this yourself. Just empty out the prop where you save your docs should be fine.

I'm still working on perfecting the integration with `vuex-easy-access` have a look at that library as well and let me know what you think : D

**Comment by davidpiesse** [comment]
Will do. 
I'll open issues if I find things but just because it's an easy way to communicate on these things.
I'll try and push fixes if I can 😁
